### ISSUE TITLE
Distributed wallet name is different for each shard

### ISSUE THREAD

**Issue by schonex** [p2p-org/dkc#35]
**Describe the bug**
The name generated for each wallet shard is different and not uniform across the the various shards

**Expected behavior**
It seems like a random UUID is used as a name for the distributed wallet when using the split command.  That's fine although unintuitive, but the name would have to be the same across N shards to be used in dirk properly.

**System information**
Linux amd64

**Additional context**
I suggest offering a config item that would allow using a logical name, rather than a random UUID.

**Comment by SpontaneousOverthrow** [comment]
Thanks, gonna fix it in a few days.

**Comment by SpontaneousOverthrow** [comment]
I have just checked and the wallet `name` field is generated the same between all `N` shards. 

Tested using this [workflow](https://github.com/p2p-org/dkc/blob/main/.github/workflows/func-tests.yaml)
Here is an example:
```
$ cat .github/examples/testswalletname/old1/459cf77c-bd8b-4459-9a3b-d69d4431b52c/459cf77c-bd8b-4459-9a3b-d69d4431b52c
{"name":"bde7b8a9-a2b6-4c10-bc8e-ca533bc32a3f","type":"distributed","uuid":"459cf77c-bd8b-4459-9a3b-d69d4431b52c","version":1}

$ cat .github/examples/testswalletname/old2/17223fd3-77bc-471a-9e08-bf4d8a3bc361/17223fd3-77bc-471a-9e08-bf4d8a3bc361
{"name":"bde7b8a9-a2b6-4c10-bc8e-ca533bc32a3f","type":"distributed","uuid":"17223fd3-77bc-471a-9e08-bf4d8a3bc361","version":1}

$ cat .github/examples/testswalletname/old3/7ace475b-d4c2-4a1d-bb69-359957e94017/7ace475b-d4c2-4a1d-bb69-359957e94017
{"name":"bde7b8a9-a2b6-4c10-bc8e-ca533bc32a3f","type":"distributed","uuid":"7ace475b-d4c2-4a1d-bb69-359957e94017","version":1}
```
@schonex can you provide more info about the error?

**Comment by schonex** [comment]
When I run `dkc 0.0.9` I get the following result:

```
$ cat 1/621271dc-3242-4009-b6ab-6f6c8497e549/621271dc-3242-4009-b6ab-6f6c8497e549                                                                                              
{"name":"1ba292e2-a18a-4b23-9cce-7b5b265a42ee","type":"distributed","uuid":"621271dc-3242-4009-b6ab-6f6c8497e549","version":1}

$ cat 2/8b63159f-3ab3-4cf4-8af7-0e88fcf777b8/8b63159f-3ab3-4cf4-8af7-0e88fcf777b8                                                                                             
{"name":"bcedce6d-bf20-461a-8458-a97d9c43d528","type":"distributed","uuid":"8b63159f-3ab3-4cf4-8af7-0e88fcf777b8","version":1}

$ cat 3/a5ada956-f896-4786-bd68-b5fa5c9c8110/a5ada956-f896-4786-bd68-b5fa5c9c8110                                                                                              
{"name":"4ca79609-e684-4900-8c71-750668d87fd0","type":"distributed","uuid":"a5ada956-f896-4786-bd68-b5fa5c9c8110","version":1}
```

**Comment by SpontaneousOverthrow** [comment]
The wallet `UUID`(this is also the name of the wallet directory) is generating in the underlying [library](https://github.com/wealdtech/go-eth2-wallet-distributed/blob/master/wallet.go#L120). 
Now the `name` of the output distributed wallet [is different from the original wallet](https://github.com/p2p-org/dkc/blob/main/utils/wallets.go#L49), but we are going to preserve it in the next release.

It is very strange that you have distributed wallets with the different wallets names after the split.

Can you provide your config file? 
Do you have the same error on our test wallets(you can find them [here](https://github.com/p2p-org/dkc/tree/main/.github/examples/wallets))?

**Comment by schonex** [comment]
> Can you provide your config file? 
```
distributed-wallets:                #Distributed-wallets section
  path: /home/me/dkc/dirk                    #Path to distributed wallet (Default: None)
  passphrases: /home/me/dkc/password    #Path to file containing passphrases for unlocking/locking accounts (Default: None)
  threshold: 2                      #Threshlod value (Default: None)
  peers:                            #Peers dict, number of peers must be greater than threshold value (Default: None)
    1: 192.168.1.10:52880
    2: 172.18.1.1:52880
    3: 192.168.1.20:52880
nd-wallets:                         #Non-determenistic-wallets section
  path: /home/me/dev/dkc/.github/examples/wallets/old1               #Path to non-determenistic wallet (Default: None)
  passphrases: /home/me/dev/dkc/.github/examples/passphrases.txt    #Path to file containing passphrases for unlocking/locking accounts (Default: None)
log-level: debug
```
> Do you have the same error on our test wallets(you can find them [here](https://github.com/p2p-org/dkc/tree/main/.github/examples/wallets))?

Yes I do.

**Comment by schonex** [comment]
I think the problem is that `CreateDWallet` is run once per peer, and then this line gets called anew each time:

https://github.com/p2p-org/dkc/blob/main/utils/wallets.go#L49

Generating a new UUID for each single shard as the name of the wallet.

**Comment by SpontaneousOverthrow** [comment]
Do you have several wallets in one store? If so, we are now fixing this bug here https://github.com/p2p-org/dkc/issues/36

**Comment by schonex** [comment]
No I do not.  Only several accounts but that doesn't make a differnce, I tried deleting them and bringing it down to 1 account.

**Comment by SpontaneousOverthrow** [comment]
@selfuryon can you take a look please, I can't reproduce this error. Tried on Linux machine too.

**Comment by schonex** [comment]
do you start with a mnemonic based wallet? @SpontaneousOverthrow

**Comment by SpontaneousOverthrow** [comment]
fixed this one and added hd wallets support here https://github.com/p2p-org/dkc/pull/49
