### ISSUE TITLE
Combine uses passphrasesOut instead of In to open existing keystores

### ISSUE THREAD

**Issue by schonex** [p2p-org/dkc#44]
**Describe the bug**
combine helper command uses the passphrasesOut instead of passphrasesIn to open the sharded (distributed) keystores.

**Expected behavior**
I believe these two commands should be called with `cr.passphrasesIn`

https://github.com/p2p-org/dkc/blob/main/cmd/combine/helpers.go#L175
https://github.com/p2p-org/dkc/blob/main/cmd/combine/helpers.go#L181

**Comment by SpontaneousOverthrow** [comment]
fixed here https://github.com/p2p-org/dkc/pull/49
